<!doctype html>
<!--
  Minimal Mistakes Jekyll Theme 4.9.0 by Michael Rose
  Copyright 2013-2018 Michael Rose - mademistakes.com | @mmistakes
  Free for personal and commercial use under the MIT license
  https://github.com/mmistakes/minimal-mistakes/blob/master/LICENSE.txt
-->
<html lang="en" class="no-js">
  <head>
    <meta charset="utf-8">

<!-- begin _includes/seo.html --><title>Chocolate Chip Cookies - Minimal Mistakes</title>
<meta name="description" content="A chocolate chip cookie is a drop cookie that originated in the United States and features chocolate chips as its distinguishing ingredient.">



<meta property="og:type" content="website">
<meta property="og:locale" content="en_US">
<meta property="og:site_name" content="Minimal Mistakes">
<meta property="og:title" content="Chocolate Chip Cookies">
<meta property="og:url" content="https://mmistakes.github.io/minimal-mistakes/recipes/chocolate-chip-cookies/">


  <meta property="og:description" content="A chocolate chip cookie is a drop cookie that originated in the United States and features chocolate chips as its distinguishing ingredient.">



  <meta property="og:image" content="https://mmistakes.github.io/minimal-mistakes/assets/images/site-logo.png">



  <meta name="twitter:site" content="@mmistakes">
  <meta name="twitter:title" content="Chocolate Chip Cookies">
  <meta name="twitter:description" content="A chocolate chip cookie is a drop cookie that originated in the United States and features chocolate chips as its distinguishing ingredient.">
  <meta name="twitter:url" content="https://mmistakes.github.io/minimal-mistakes/recipes/chocolate-chip-cookies/">

  
    <meta name="twitter:card" content="summary">
    
      <meta name="twitter:image" content="https://mmistakes.github.io/minimal-mistakes/assets/images/site-logo.png">
    
